//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

#![allow(unused_imports)]

pub use super::session::Entity as Session;
pub use super::user::Entity as User;
pub use super::vault::Entity as Vault;
