//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "vault")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub vault: String,
    pub salt: String,
    pub iterations: i32,
    pub vaultiv: String,
    // Verifier derived from the master password client-side. It is an
    // authentication credential only — never the password, wrapping key, or
    // vault key. The server uses it solely to confirm a correct unlock.
    pub vault_verifier: String,
    pub created_at: DateTimeUtc,
    pub version: i32,
    pub crypto_version: i32,
    pub vault_key_wrap: Option<String>,
    pub vault_key_wrap_iv: Option<String>,
    // Global lock signal for web ↔ extension consistency. Monotonic counter,
    // bumped by POST /api/lock; peers compare it in GET /session and wipe
    // local keys on a bump. Non-sensitive: never key material or plaintext.
    pub lock_epoch: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
